'use strict'

const test = require('node:test')
const assert = require('node:assert')
const { extractSessionName } = require('../lib/claude-session-name')

/**
 * A Claude Code session is named after its first REAL user message (IRIS chat Sessions tab).
 *
 * Measured 2026-09-17 on a phone: sessions listed as "/recap recap" and "/model model". The first
 * user message was a bare slash command — `<command-name>/recap</command-name>
 * <command-message>recap</command-message><command-args></command-args>` — and stripping the tags
 * glued name and message together. A bare command says nothing about the work; skip it.
 */

const user = (content) => JSON.stringify({ type: 'user', message: { role: 'user', content } })
const cmd = (name, args = '') =>
  user(`<command-name>/${name}</command-name>\n            <command-message>${name}</command-message>\n            <command-args>${args}</command-args>`)

test('a bare slash command is skipped for the next real message', () => {
  assert.strictEqual(extractSessionName([cmd('recap'), user('can we finish this ticket out')], '/code/x'), 'can we finish this ticket out')
  assert.strictEqual(extractSessionName([cmd('model'), cmd('login'), user('fix the picker')], '/code/x'), 'fix the picker')
})

test('a slash command WITH arguments is the name — the arguments are the work', () => {
  assert.strictEqual(extractSessionName([cmd('work-the-epic', 'start with step 1')], '/code/x'), '/work-the-epic start with step 1')
})

test('command output, caveats and interruptions are not names', () => {
  const lines = [
    user('<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>'),
    user('<local-command-stdout>Set model to `Opus 5`</local-command-stdout>'),
    user([{ type: 'text', text: '[Request interrupted by user for tool use]' }]),
    user('the real ask'),
  ]
  assert.strictEqual(extractSessionName(lines, '/code/x'), 'the real ask')
})

test('a system reminder is removed with its content, not merely untagged', () => {
  assert.strictEqual(extractSessionName([user('<system-reminder>Codebase and user instructions are shown below</system-reminder>\nfix the gate')], '/code/x'), 'fix the gate')
  assert.strictEqual(extractSessionName([user('<system-reminder>only a reminder</system-reminder>'), user('second message')], '/code/x'), 'second message')
})

test('ordinary messages keep working: text blocks, tool results ignored, long text trimmed', () => {
  assert.strictEqual(extractSessionName([user([{ type: 'tool_result', content: 'x' }]), user([{ type: 'text', text: 'hello there' }])], '/code/x'), 'hello there')
  const long = 'a'.repeat(120)
  assert.strictEqual(extractSessionName([user(long)], '/code/x'), 'a'.repeat(77) + '...')
  assert.strictEqual(extractSessionName([user('  lots   of\n\n space  ')], '/code/x'), 'lots of space')
})

test('/clear and short noise are still skipped (existing behaviour)', () => {
  assert.strictEqual(extractSessionName([user('/clear'), user('ok'), user('build step five')], '/code/x'), 'build step five')
})

test('nothing usable falls back to the project folder, then a generic name', () => {
  assert.strictEqual(extractSessionName([cmd('recap'), 'not json', JSON.stringify({ type: 'assistant' })], '/Users/me/sites/freelabel/'), 'freelabel')
  assert.strictEqual(extractSessionName([], null), 'Coding Session')
})
